name: Update mirrors on a schedule
on:
  schedule:
    - cron: '0,15,30,45 * * * *'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Cache PyPI packages
        uses: actions/cache@v2
        env:
          cache-name: pip-cache
        with:
          path: .cache/pip
          key: ${{ runner.os }}-mirror-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-mirror-${{ env.cache-name }}-
            ${{ runner.os }}-mirror-
            ${{ runner.os }}-

      - name: Cache octave converted git repository
        uses: actions/cache@v2
        env:
          cache-name: git-cache
        with:
          path: octave
          key: ${{ runner.os }}-mirror-${{ env.cache-name }}-${{ hashFiles('*.sh') }}
          restore-keys: |
            ${{ runner.os }}-mirror-${{ env.cache-name }}-
            ${{ runner.os }}-mirror-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libcurl4-gnutls-dev libpcre2-dev python3-dev zlib1g-dev

      - name: Initialize
        run: bash -ex init.sh

      - name: Pull
        run: bash -ex pull.sh

      - name: Push to mirror on GitHub
        run: bash -ex push.sh github ${{ secrets.REMOTE_URL_GITHUB }}

      - name: Push to mirror on GitLab
        run: bash -ex push.sh gitlab ${{ secrets.REMOTE_URL_GITLAB }}
